name: ditel_sms_app
description: Application d'envois des messages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #Utility Packages
  http: ^1.2.0
  #intl: ^0.19.0
  intl: any
  logger: ^2.0.1
  url_launcher: ^6.1.12
  percent_indicator: ^4.2.3
  file_picker: ^6.1.1
  open_app_file: ^4.0.2
  easy_search_bar: ^2.5.0


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #State management
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1
  intl_phone_field: ^3.2.0
  stylish_dialog: ^1.0.2
  quickalert: ^1.0.2
  toastification: ^1.2.0
  multiple_search_selection: ^2.6.1
  csv: ^5.1.1
  flutter_web_pagination: ^0.0.3
  infinite_scroll_pagination: ^4.0.0
  syncfusion_flutter_datagrid: ^24.2.5
  number_paginator: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/brands/
    - assets/icons/
    - assets/images/dashboard/


  fonts:
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LatoLight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: LatoBoldItalic
      fonts:
        - asset: assets/fonts/Lato-BoldItalic.ttf
    - family: LatoThin
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf

